title: "Cathryn Usman (Mamie Usman)"
logo: /assets/img/Data.jpg
description: "Portfolio of Cathryn Usman, also known as Mamie Usman. A Data Analyst skilled in Advanced Excel, Power BI and SQL."
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
